// In-memory view state for the GUI shell. Mirror of the TUI's `AppState`
// shape (`crates/atelier-tui/src/lib.rs`) — the same fields, the same
// invariants, the same apply() reducer logic. The two surfaces share a
// data contract because they consume the same `atelier://event` broadcast
// stream.
//
// Pure functions only — no DOM, no Svelte runes. Components import this
// module and wrap the state in `$state` themselves. This split keeps the
// state-mutation logic exercisable in isolation if a vitest harness ever
// lands.

// ---- BridgedEvent shape from the Rust side ----
//
// The Rust shell projects `atelier_core::session::Event` onto the JSON
// shape below via `bridge_event` (see `crates/atelier-gui/src/lib.rs`).
// The frontend matches on `kind` and reads the per-variant `payload`.

export type BridgedEvent = {
  kind: string
  payload: unknown
}

// ---- Domain types — match the Rust producer side ----

export type ConversationRole = 'user' | 'assistant' | 'tool' | 'system'

export type ConversationLine =
  | {
      kind?: undefined  // backward-compat: existing text lines have no kind field
      role: ConversationRole
      text: string
    }
  | {
      kind: 'failure_card'
      title: string
      cause: string
      message: string
      fixHint: string | null
      memoryCardPath: string | null
      retryCommand: string
      retryPrompt: string
    }

// Mirror of `atelier_core::ledger::LedgerEntry`. Serde tag is `kind`.
export type LedgerEntry =
  | {
      kind: 'model_call'
      timestamp: string
      model_id: string
      prompt_tokens: number
      completion_tokens: number
      cached_tokens?: number | null
      cost_usd?: number | null
      tool_name?: string
    }
  | {
      kind: 'tool_call'
      timestamp: string
      tool_name: string
      cost_usd?: number | null
    }
  | {
      kind: 'cache_bust'
      timestamp: string
      note: string
    }

// ---- AppState — the single source of truth for the UI ----

/// Default context-window denominator. Mirrors
/// `DEFAULT_CONTEXT_WINDOW_TOKENS` in atelier-tui (200k = Anthropic
/// Sonnet/Opus 4.x).
export const DEFAULT_CONTEXT_WINDOW_TOKENS = 200_000

/// Cap on remembered conversation lines. Matches the TUI's
/// `MAX_CONVERSATION_LINES`.
export const MAX_CONVERSATION_LINES = 1_000

/// Cap on the raw event log (newest-first). Matches `MAX_EVENT_LOG`.
export const MAX_EVENT_LOG = 1_000

export type EventLogEntry = {
  ts: string
  kind: string
  detail: string
}

/// v53 — one row in the §5 Context panel. Mirror of
/// `atelier_core::context::ContextItemSummary`; bridged across
/// `atelier://event` as the payload of the `ContextItems` event.
export type ContextItemSummary = {
  id: string
  kind: string
  label: string
  provenance: string
  provenance_detail?: string | null
  tokens: number
  /// `exact` / `approx` / `unavailable`.
  token_source: string
  pinned: boolean
}

/// v54 — one row in the §5 Memory panel. Mirror of
/// `atelier_core::memory::MemoryCardSummary`; bridged across
/// `atelier://event` as the payload of the `MemoryCards` event.
export type MemoryCardSummary = {
  id: string
  title: string
  body_preview: string
  /// RFC 3339.
  created_at: string
  /// RFC 3339.
  last_used: string
  pinned: boolean
  /// v60.5 — present (as the count of replaced items) when this
  /// card was generated by §5 non-destructive compaction. The
  /// Memory pane renders a "compacted from N items" hint when set;
  /// the v60.6 Expand affordance gates on this field.
  compacted_from?: number
  /// v60.6 — prompt-cache rewarm cost the user pays if they Expand.
  /// Sum of `tokens.count` across the items that were replaced by
  /// this card at compaction time. Set iff `compacted_from` is set.
  /// Surfaced in the Expand confirm dialog so the cost disclosure
  /// matches the operation about to run.
  cache_rewarm_tokens?: number
}

/// Phase C close — §5 mental-model panel state. Mirror of
/// `atelier_core::mental_model::MentalModelSnapshot`. `enabled`
/// defaults to `false` (off until the user opts in); the
/// `updated_at` field is empty until the first set.
///
/// **Cost disclosure (v60.20)**: when `enabled && text.trim() !== ''`
/// the runner injects `text` as a second System message on every
/// per-turn `adapter.chat` call. The panel's badge renders
/// `~text_tokens tokens / turn` in that state and `0 tokens / turn`
/// otherwise.
export type MentalModel = {
  enabled: boolean
  text: string
  text_tokens: number
  updated_at: string
}

export function initialMentalModel(): MentalModel {
  return { enabled: false, text: '', text_tokens: 0, updated_at: '' }
}

/// v62 — §7 verify-pass tier label. Mirror of Rust's
/// `VerificationTier` (serde `rename_all = "snake_case"` /
/// `wire_label()` agree by construction; pinned by the Rust test
/// `verification_tier_wire_labels_agree_with_serde`).
///
///   * `tier1_lsp` — LSP-driven hallucination detector (Tier 1).
///     Gated on Q3; no producer wired yet. Future-reserved.
///   * `tier2_tree_sitter` — tree-sitter syntactic checks (Tier 2).
///   * `tier3_textual` — textual lying-agent detector (Tier 3).
///     The fallback; always available.
///   * `not_run` — no verify pass ran this turn.
export type VerificationTier =
  | 'tier1_lsp'
  | 'tier2_tree_sitter'
  | 'tier3_textual'
  | 'not_run'

/// v62 — §7 verify-pass terminal state. Rendered by `MetersPane`
/// as a small badge so the user can see which tier (and therefore
/// how much hallucination coverage) ran on the last verify pass.
/// Populated by `VerificationPassed` events; defaults to `not_run`
/// before any verify pass happens.
export type VerificationStatus = {
  tier: VerificationTier
  file_count: number
  claim_count: number
}

export function initialVerificationStatus(): VerificationStatus {
  return { tier: 'not_run', file_count: 0, claim_count: 0 }
}

/// v60.7 §1 BYOM — one cell of the capability matrix. Mirrors
/// Rust's `CapabilityClaim` (serde rename_all=snake_case).
export type CapabilityClaim = 'supported' | 'claimed_but_broken' | 'unsupported'

/// v60.7 §1 BYOM — provenance for a capability matrix row. Mirrors
/// Rust's `CapabilityRowSource`.
export type CapabilityRowSource = 'static' | 'adapter' | 'probe'

/// v60.7 §1 BYOM — capability matrix row for the active model.
/// Mirror of `atelier_core::adapter::capability_matrix::CapabilityMatrixRow`.
/// Surfaced as a tooltip + sublabel on the footer's model badge.
export type CapabilityMatrixRow = {
  model_id: string
  display_label: string
  native_tool_use: CapabilityClaim
  streaming: CapabilityClaim
  vision: CapabilityClaim
  prompt_cache: CapabilityClaim
  structured_output: CapabilityClaim
  long_context: CapabilityClaim
  context_window_tokens: number
  source: CapabilityRowSource
}

export type SuitabilityGrade = 'excellent' | 'good' | 'marginal' | 'poor'

export type SuitabilityFactor = {
  name: string
  awarded: number
  max: number
  detail: string
}

export type ModelSuitability = {
  model_id: string
  score: number
  grade: SuitabilityGrade
  recommendation: string
  factors: SuitabilityFactor[]
  strengths: string[]
  risks: string[]
}

/// v52 — the active BYOM model, populated by `ModelProfileLoaded`.
/// Rendered in the footer (`App.svelte`) on the right-hand side so the
/// user always knows which model + strategy the run is using.
/// `null` until the Runner emits its one-shot `ModelProfileLoaded`
/// event at session start.
export type CurrentModel = {
  /// `<provider>:<model>`, e.g. `local:qwen2.5-coder:7b`.
  modelId: string
  /// `http://localhost:11434/v1` etc. Empty for adapters that don't
  /// speak HTTP (mock / anthropic).
  baseUrl: string
  /// `native_tool` / `json_sentinel` / `regex_prose`. See
  /// `atelier_core::protocol_strategy::Strategy`.
  strategy: string
  /// `cache_hit` / `probed` / `reprobed` / `not_cached`. See
  /// `atelier_core::adapter::model_profile::ProbeLoadOutcome`.
  outcome: string
  /// v60.7 §1 BYOM — capability matrix row for this model.
  /// Surfaced as a tooltip on the badge; `null` until the
  /// Runner emits a `ModelProfileLoaded` carrying it.
  capabilityRow: CapabilityMatrixRow | null
  suitability: ModelSuitability | null
}

/// §10 — one row in the sub-agent panel. Updated by the 5 SubagentXxx
/// bus events. Mirrors `SubagentEntry` in `crates/atelier-tui/src/lib.rs`.
export type SubagentEntry = {
  id: string
  subagentType: string
  description: string
  status: string // "running" | "completed" | "failed" | "cancelled"
  turn: number
  maxTurns: number
  promptTokens: number
  completionTokens: number
  cachedTokens: number
  /// User-turn index in which this sub-agent was spawned (mirrors the TUI's
  /// `SubagentEntry.generation`). Sub-agents from the current generation
  /// render in full; earlier generations collapse into a single "prior"
  /// rollup in `SubagentPane`.
  generation: number
}

export type AppState = {
  events: EventLogEntry[]
  currentState: string
  conversation: ConversationLine[]
  totalCostUsd: number
  contextTokens: { known: number; unknown: number }
  contextWindowTokens: number
  // Scrub UI state. `null` = HEAD (live); `n` = pinned `n` steps back.
  // Phase D §4 owns the actual time-travel machinery; the GUI just
  // records intent the same way the TUI does.
  scrubOffset: number | null
  /// v52 — active BYOM model. See [`CurrentModel`].
  currentModel: CurrentModel | null
  /// v53 — §5 Context panel rows. Replaced wholesale on each
  /// `ContextItems` event; populated by the Runner at every turn
  /// boundary alongside the aggregate `ContextSnapshot`.
  contextItems: ContextItemSummary[]
  /// v54 — §5 Memory panel rows. Replaced wholesale on each
  /// `MemoryCards` event; populated by the Runner alongside
  /// `ContextItems`. Distinct from context items: cards are
  /// durable across sessions; context items are per-turn.
  memoryCards: MemoryCardSummary[]
  /// Phase C close — §5 mental-model panel state. Hydrated by an
  /// initial `snapshot_mental_model` Tauri call (App.svelte) and
  /// updated by `MentalModelSnapshot` events from the bus. Defaults
  /// to off so the panel stays hidden until the user opts in via
  /// the header toggle.
  mentalModel: MentalModel
  /// v61 — §14 concurrent-edit modal state. `null` when no external
  /// edit is pending; populated by `FilesChanged`, cleared by
  /// `FilesChangedAcknowledged`. The webview renders
  /// `ConcurrentEditModal.svelte` when this is non-null.
  concurrentEditModal: { paths: string[]; observedAt: string } | null
  /// v60.28 H2 follow-on — adapter-swap consent modal state. `null`
  /// when no swap is pending the user's accept/reject; populated by
  /// `AdapterSwapPending`, cleared by `AdapterSwapped` (accepted) or
  /// `AdapterSwapRejected` (refused / timed out). The webview renders
  /// `SwapConsentModal.svelte` when this is non-null; the modal calls
  /// the `respond_to_swap` Tauri command keyed by `swapId`.
  pendingSwap: { swapId: string; toModelId: string; baseUrl: string } | null
  /// Prompt/completion token counts for the most recent model call.
  /// Updated by every `LedgerAppended` event whose entry is a
  /// `model_call`; null until the first call lands.
  lastTurnTokens: { prompt: number; completion: number; cached: number } | null
  /// Streaming assistant text accumulator. Non-empty while a chat turn
  /// is in flight (`AssistantTextDelta` events append here). Cleared to
  /// '' when the turn's `MessageCommitted { role: assistant }` lands.
  streamingAssistant: string
  /// v62 — §7 verify-pass tier indicator. Defaults to `not_run`.
  verificationStatus: VerificationStatus
  /// v60.9 B1 follow-on — most recent §1 context-overflow resolution.
  /// Populated by `ContextOverflowResolved`; `null` before any
  /// overflow has been resolved. `MetersPane` renders a transient
  /// toast/badge keyed off the `at` timestamp; consumers can compare
  /// `Date.now() - at` against their own decay window (the pane uses
  /// ~5s) to fade the toast back out. The reducer never auto-clears
  /// this field — the badge stays in the DOM but the toast styling
  /// drops off once the decay window elapses, so a debug surface
  /// can still inspect the last resolution after the toast fades.
  lastOverflowResolution: {
    resolution: string
    freed_tokens: number | null
    items_compacted: number | null
    at: number
  } | null
  /// §10 sub-agent panel rows. Populated by SubagentSpawned, updated by
  /// SubagentTurnAdvanced / SubagentCompleted / SubagentCancelled events.
  subagents: SubagentEntry[]
  /// Monotonic user-turn counter (mirrors the TUI's `current_generation`).
  /// Incremented on every committed user message; newly-spawned sub-agents
  /// are tagged with this value so `SubagentPane` can demote prior-run
  /// sub-agents (generation `< currentGeneration`) into a collapsed rollup.
  currentGeneration: number
  /// AgentStalled timestamp (ms since epoch). Non-null while the runner is
  /// waiting for the user to nudge after the model replied without tool calls
  /// or a claimed_done envelope. Cleared when the user submits the next turn.
  stalledAt: number | null
  /// True from RunStarted until RunFinished. Covers the dead zone before the
  /// first real event arrives (model probe, session setup, etc.).
  runInFlight: boolean
  /// v60.71 U10 — §7 Tier-1 LSP first-use install request. `null` when no
  /// install prompt is pending; populated by `RequestLspInstall`, cleared by
  /// `LspInstallResolved` or when the user approves / declines. The webview
  /// renders `LspInstallModal.svelte` (or an inline prompt) when non-null.
  lspInstallRequest: { language: string; candidates: string[] } | null
  /// Provider-health UX (L1-3) — reachability of the active OpenAI-compat
  /// adapter's endpoint. `null` = no claim (Mock, Anthropic, unchecked).
  /// Reset to `null` on ModelProfileLoaded so stale health from a prior
  /// profile can't survive a swap. Populated by EndpointHealthChanged.
  endpointHealth: { status: 'reachable' | 'unreachable'; checkedAt: number; error: string | null } | null
  /// Provider-health UX (L1-4) — `false` when the context-window
  /// denominator is the conservative 8,192 fallback (probe returned no
  /// max_model_len). Rule: unverified iff capability_row.source === 'adapter'
  /// && !window_verified. Reset to `true` on ModelProfileLoaded; set by
  /// EndpointHealthChanged once the trailing health event arrives.
  contextWindowVerified: boolean
  /// Provider-health UX (L3-2) — transient recovery toast. Set when health
  /// transitions unreachable → reachable. Cleared after rendering the toast.
  recoveryToast: { text: string; at: number } | null
}

export function initialState(): AppState {
  return {
    events: [],
    currentState: '',
    conversation: [],
    totalCostUsd: 0,
    contextTokens: { known: 0, unknown: 0 },
    contextWindowTokens: DEFAULT_CONTEXT_WINDOW_TOKENS,
    scrubOffset: null,
    currentModel: null,
    contextItems: [],
    memoryCards: [],
    mentalModel: initialMentalModel(),
    concurrentEditModal: null,
    pendingSwap: null,
    lastTurnTokens: null,
    streamingAssistant: '',
    verificationStatus: initialVerificationStatus(),
    lastOverflowResolution: null,
    subagents: [],
    currentGeneration: 0,
    stalledAt: null,
    runInFlight: false,
    lspInstallRequest: null,
    endpointHealth: null,
    contextWindowVerified: true,
    recoveryToast: null,
  }
}

// v60.37 B6/UI-5 — runtime payload guard. In dev (`import.meta.env.DEV`),
// asserts that the event payload has every required field; in prod, the
// existing silent-coerce behaviour is preserved (so a single wire-label
// drift on a non-critical event doesn't take the whole UI down).
//
// v60.100 — in prod, emits a console.warn once per event kind on shape
// mismatch so wire-label drift is at least visible in DevTools without
// crashing the UI. A module-level Set caps noise to one warning per kind.
//
// Used by the highest-stakes arms (modal triggers, consent-flow events).
// The lower-stakes arms keep the raw `as X` cast pattern for now; promote
// them here as they grow new required fields.
const _castPayloadWarnedKinds = new Set<string>()
function castPayload<T>(
  payload: unknown,
  required: readonly string[],
  kind: string,
): T {
  if (import.meta.env?.DEV && (typeof payload !== 'object' || payload == null)) {
    throw new Error(
      `state.ts: ${kind} payload must be an object; got ${typeof payload}`,
    )
  }
  if (import.meta.env?.DEV && typeof payload === 'object' && payload != null) {
    for (const k of required) {
      if (!(k in (payload as Record<string, unknown>))) {
        throw new Error(`state.ts: ${kind} payload missing required field '${k}'`)
      }
    }
  }
  if (!import.meta.env?.DEV && typeof payload === 'object' && payload != null) {
    for (const k of required) {
      if (!(k in (payload as Record<string, unknown>))) {
        if (!_castPayloadWarnedKinds.has(kind)) {
          _castPayloadWarnedKinds.add(kind)
          console.warn(
            `[atelier] state.ts: ${kind} payload missing field '${k}' — possible wire-label drift. Coercing.`,
          )
        }
      }
    }
  }
  return payload as T
}

// ---- applyEvent: pure reducer ----
//
// Returns a NEW state object (no in-place mutation) so Svelte's `$state`
// reactivity proxy can diff cleanly. Mirror of `AppState::apply` in
// `crates/atelier-tui/src/lib.rs`.

export function applyEvent(state: AppState, evt: BridgedEvent): AppState {
  const logged = { ...projectEvent(evt), ts: nowTimestamp() }
  const events = pushBoundedNewest(state.events, logged, MAX_EVENT_LOG)

  switch (evt.kind) {
    case 'Transitioned': {
      const p = evt.payload as { from: string; to: string }
      return { ...state, events, currentState: p.to }
    }
    case 'MessageCommitted': {
      const p = evt.payload as { role: ConversationRole; text: string }
      // v58 (stale-comment fix) — the bridge now serialises Rust's
      // `MessageRole` via `MessageRole::wire_label()` (canonical
      // lowercase). The defensive coercion stays as a guard against a
      // future variant added Rust-side that the GUI doesn't yet know
      // about — surfaces as "system" rather than a blank prefix.
      const role: ConversationRole = isConversationRole(p.role) ? p.role : 'system'
      const line: ConversationLine = { role, text: p.text }
      const conversation = pushBounded(state.conversation, line, MAX_CONVERSATION_LINES)
      // Clear streaming buffer when assistant turn finalises.
      // Reset token meter to 0 when a new user turn starts so the
      // incremental completion count is visible from zero.
      const streamingAssistant = role === 'assistant' ? '' : state.streamingAssistant
      const lastTurnTokens = role === 'user'
        ? { prompt: 0, completion: 0, cached: 0 }
        : state.lastTurnTokens
      // A new user turn clears the stalled banner.
      const stalledAt = role === 'user' ? null : state.stalledAt
      // A new user turn opens the next generation, demoting any sub-agents
      // from earlier runs into the collapsed rollup.
      const currentGeneration = role === 'user'
        ? state.currentGeneration + 1
        : state.currentGeneration
      return {
        ...state,
        events,
        conversation,
        streamingAssistant,
        lastTurnTokens,
        stalledAt,
        currentGeneration,
      }
    }
    case 'AssistantTextDelta': {
      const p = evt.payload as { delta: string }
      const streamingAssistant = state.streamingAssistant + (p.delta ?? '')
      // Estimate completion tokens from streamed chars (≈4 chars/token).
      const completionEst = Math.round(streamingAssistant.length / 4)
      const lastTurnTokens = {
        prompt: state.lastTurnTokens?.prompt ?? 0,
        completion: completionEst,
        cached: state.lastTurnTokens?.cached ?? 0,
      }
      return { ...state, events, streamingAssistant, lastTurnTokens }
    }
    case 'LedgerAppended': {
      const p = evt.payload as { entry: LedgerEntry }
      const c = ledgerEntryCost(p.entry)
      const totalCostUsd = c == null ? state.totalCostUsd : state.totalCostUsd + c
      if (p.entry.kind === 'model_call') {
        const lastTurnTokens = {
          prompt: p.entry.prompt_tokens ?? 0,
          completion: p.entry.completion_tokens ?? 0,
          cached: p.entry.cached_tokens ?? 0,
        }
        return { ...state, events, totalCostUsd, lastTurnTokens }
      }
      return { ...state, events, totalCostUsd }
    }
    case 'ContextSnapshot': {
      const p = evt.payload as { known_tokens: number; unknown_tokens: number }
      return {
        ...state,
        events,
        contextTokens: { known: p.known_tokens, unknown: p.unknown_tokens },
      }
    }
    case 'ModelProfileLoaded': {
      const p = evt.payload as {
        model_id: string
        base_url: string
        strategy: string
        outcome: string
        capability_row?: CapabilityMatrixRow | null
        suitability?: ModelSuitability | null
      }
      const currentModel: CurrentModel = {
        modelId: p.model_id,
        baseUrl: p.base_url,
        strategy: p.strategy,
        outcome: p.outcome,
        capabilityRow: p.capability_row ?? null,
        suitability: p.suitability ?? null,
      }
      const contextWindowTokens =
        p.capability_row && p.capability_row.context_window_tokens > 0
          ? p.capability_row.context_window_tokens
          : state.contextWindowTokens
      // F1b: only reset health state when the model identity actually changed.
      // The Runner re-emits ModelProfileLoaded for the *same* model mid-run
      // (runner.rs:~2678) — an unconditional reset wiped the health dot on
      // every agent turn. Compare model_id only; do NOT compare base_url:
      // GUI-side profiles use skipped_for_well_known which hard-codes
      // base_url:"", while the Runner carries the real base_url — a base_url
      // comparison mismatches on every agent run and defeats the fix.
      const identityChanged = state.currentModel?.modelId !== p.model_id
      return {
        ...state,
        events,
        currentModel,
        contextWindowTokens,
        // Reset health only on a real identity change; preserve across same-model
        // re-emissions (Runner probe refresh, redundant hydrates).
        endpointHealth: identityChanged ? null : state.endpointHealth,
        contextWindowVerified: identityChanged ? true : state.contextWindowVerified,
        // Clear toast on swap — "X back online" must not survive a switch to Y.
        recoveryToast: identityChanged ? null : state.recoveryToast,
      }
    }
    case 'EndpointHealthChanged': {
      const p = evt.payload as {
        model_id: string
        base_url: string
        status: 'reachable' | 'unreachable'
        checked_at: string
        window_verified: boolean
        max_model_len: number | null
        error: string | null
      }
      const endpointHealth = {
        status: p.status,
        checkedAt: Date.now(),
        error: p.error ?? null,
      }
      // Update contextWindowTokens when the probe found max_model_len.
      const contextWindowTokens = p.window_verified && p.max_model_len != null
        ? p.max_model_len
        : state.contextWindowTokens
      // Unverified iff source='adapter' && !window_verified.
      // adapter-sourced rows are the 8,192 seed; static/probe rows are trusted.
      const isAdapterSourced =
        state.currentModel?.capabilityRow?.source === 'adapter'
      const contextWindowVerified = isAdapterSourced ? p.window_verified : true
      // F4: recovery toast lifecycle.
      // - unreachable → reachable: set the toast (endpoint came back).
      // - any unreachable event: clear the toast ("back online" next to a red
      //   dot is misleading; a flap must clear the prior toast immediately).
      // - repeated reachable events: preserve (don't cut mid-animation short).
      const wasUnreachable = state.endpointHealth?.status === 'unreachable'
      const nowReachable = p.status === 'reachable'
      const modelId = state.currentModel?.modelId ?? p.model_id
      const recoveryToast = !nowReachable
        ? null  // clear on any unreachable event
        : wasUnreachable
          ? { text: `${modelId} is back online`, at: Date.now() }
          : state.recoveryToast  // preserve for repeated reachable polls
      return {
        ...state,
        events,
        endpointHealth,
        contextWindowTokens,
        contextWindowVerified,
        recoveryToast,
      }
    }
    case 'ProviderFailure': {
      // L2-2 — append a failure card to the conversation so the user
      // sees an actionable card with Retry and Switch profile buttons.
      const p = evt.payload as {
        model_id: string
        base_url: string
        cause: string
        message: string
        fix_hint: string | null
        memory_card_path: string | null
        retry_command: string
        retry_prompt: string
      }
      const card: ConversationLine = {
        kind: 'failure_card',
        title: `${p.cause} — ${p.model_id}`,
        cause: p.cause,
        message: p.message,
        fixHint: p.fix_hint ?? null,
        memoryCardPath: p.memory_card_path ?? null,
        retryCommand: p.retry_command,
        retryPrompt: p.retry_prompt,
      }
      const conversation = pushBounded(state.conversation, card, MAX_CONVERSATION_LINES)
      return { ...state, events, conversation }
    }
    case 'ContextItems': {
      // v53 — replace the panel's items wholesale. Snapshots come
      // at every turn boundary, so a stale partial render is never
      // preferable to the freshest snapshot.
      const p = evt.payload as { items: ContextItemSummary[] }
      return { ...state, events, contextItems: p.items ?? [] }
    }
    case 'MemoryCards': {
      // v54 — same wholesale-replace policy as ContextItems.
      const p = evt.payload as { cards: MemoryCardSummary[] }
      return { ...state, events, memoryCards: p.cards ?? [] }
    }
    case 'MentalModelSnapshot': {
      // Phase C close — refresh the enabled/text_tokens fields from
      // the bus. We don't carry text on the bus (it lives in the
      // dispatcher); the panel reads it back via a Tauri snapshot
      // call when needed, and otherwise keeps the locally-edited
      // text. This avoids a round-trip storm when the user types.
      const p = evt.payload as { enabled: boolean; text_tokens: number }
      const updated: MentalModel = {
        ...state.mentalModel,
        enabled: !!p.enabled,
        text_tokens: p.text_tokens ?? 0,
      }
      return { ...state, events, mentalModel: updated }
    }
    case 'FilesChanged': {
      // v61 — §14 concurrent-edit modal opens. The dispatcher has
      // already queued the next tool call; we just surface the
      // user-decision modal. Subsequent FilesChanged bursts replace
      // the snapshot (debouncing is the watcher's job).
      // v60.37 B6 — DEV-mode shape guard. A wire-label drift on this
      // event would silently break the §14 modal flow.
      const p = castPayload<{ paths: string[]; observed_at: string }>(
        evt.payload,
        ['paths', 'observed_at'],
        'FilesChanged',
      )
      return {
        ...state,
        events,
        concurrentEditModal: {
          paths: p.paths ?? [],
          observedAt: p.observed_at ?? '',
        },
      }
    }
    case 'FilesChangedAcknowledged': {
      // v61 — close the modal regardless of which arm resolved it
      // (Reload / Wait / Pause / AutoReload / PauseTimedOut).
      return { ...state, events, concurrentEditModal: null }
    }
    case 'VerificationPassed': {
      // v62 — §7 verify-pass tier badge. Wholesale-replace the
      // verification status so the MetersPane badge reflects the
      // most recent verify pass.
      const p = evt.payload as {
        tier: string
        file_count: number
        claim_count: number
      }
      const tier = isVerificationTier(p.tier) ? p.tier : 'not_run'
      const verificationStatus: VerificationStatus = {
        tier,
        file_count: p.file_count ?? 0,
        claim_count: p.claim_count ?? 0,
      }
      return { ...state, events, verificationStatus }
    }
    case 'VerificationFailed': {
      // v60.41 — §7 verify-fail tier badge. The Rust side emits this
      // when the did-it-do-what-it-said gate finds discrepancies
      // between `claimed_changes` and the staged diff. Surfaces the
      // tier on the meters badge; the discrepancies themselves are
      // recorded in the event log via the standard `events` append
      // above. (Pre-v60.41 this fell through to the default arm,
      // which threw in DEV and crashed `applyEvent`.)
      const p = evt.payload as {
        tier: string
        discrepancy_count?: number
      }
      const tier = isVerificationTier(p.tier) ? p.tier : 'not_run'
      const verificationStatus: VerificationStatus = {
        tier,
        file_count: 0,
        claim_count: p.discrepancy_count ?? 0,
      }
      return { ...state, events, verificationStatus }
    }
    case 'ContextOverflowResolved': {
      // §1 BYOM (v60.9 B1 follow-on) — context-window asymmetry
      // resolution. Stash the most recent resolution so `MetersPane`
      // can render a transient toast. `Date.now()` captured here so
      // the decay window runs against wall-clock; the pane compares it
      // against its own elapsed-time tick to fade the toast back out.
      const p = evt.payload as {
        resolution: string
        freed_tokens: number | null
        items_compacted: number | null
      }
      return {
        ...state,
        events,
        lastOverflowResolution: {
          resolution: p.resolution,
          freed_tokens: p.freed_tokens ?? null,
          items_compacted: p.items_compacted ?? null,
          at: Date.now(),
        },
      }
    }
    case 'StrategyDegraded': {
      // §1 BYOM — refresh the strategy badge on the model footer.
      // `currentModel` is null until `ModelProfileLoaded` lands; the
      // runner emits `ModelProfileLoaded` before the first turn, so by
      // the time a degradation can fire `currentModel` is populated.
      // Guard anyway so a misordered scenario doesn't crash the reducer.
      const p = evt.payload as { from: string; to: string; reason: string }
      if (!state.currentModel) {
        return { ...state, events }
      }
      const currentModel: CurrentModel = {
        ...state.currentModel,
        strategy: p.to,
      }
      return { ...state, events, currentModel }
    }
    case 'AdapterSwapped': {
      // v60.10 §1 BYOM — log the swap. The paired `ModelProfileLoaded`
      // (which arrives next) carries the fresh model id + capability
      // row that the footer renders; this arm just refreshes the
      // event log so the user can see the transition in-stream.
      // v60.28 H2 follow-on — clear any open consent modal: an
      // `AdapterSwapped` after an `AdapterSwapPending` means the
      // renderer's reply was Accepted and the swap is now live.
      return { ...state, events, pendingSwap: null }
    }
    case 'AdapterSwapPending': {
      // v60.28 H2 follow-on — open the consent modal. `swap_adapter`
      // is now awaiting `respond_to_swap` keyed by `swap_id`; the
      // modal renders Accept / Reject buttons that invoke that
      // command. Allowlist-refused swaps never emit `Pending` (they
      // jump straight to `Rejected` with `swap_id: null`).
      // v60.37 B6 — DEV-mode shape guard. A renamed field here would
      // brick the consent flow silently in prod.
      const p = castPayload<{ swap_id: string; to_model_id: string; base_url: string }>(
        evt.payload,
        ['swap_id', 'to_model_id', 'base_url'],
        'AdapterSwapPending',
      )
      return {
        ...state,
        events,
        pendingSwap: {
          swapId: p.swap_id,
          toModelId: p.to_model_id,
          baseUrl: p.base_url,
        },
      }
    }
    case 'AdapterSwapRejected': {
      // v60.28 H2 follow-on — close the consent modal (if open). A
      // `swap_id: null` payload is an allowlist refusal that never
      // opened a modal; we still treat it as "no pending swap" so
      // any stale modal from a previous swap is cleared too.
      return { ...state, events, pendingSwap: null }
    }
    // v60.71 U10 — §7 Tier-1 LSP first-use install events.
    // `RequestLspInstall` populates `lspInstallRequest` so the
    // `LspInstallModal.svelte` can render the approval prompt.
    // `LspInstallResolved` clears it.
    case 'RequestLspInstall': {
      const p = evt.payload as {
        language?: string
        candidate_packages?: string[]
      }
      return {
        ...state,
        events,
        lspInstallRequest: {
          language: p.language ?? '',
          candidates: p.candidate_packages ?? [],
        },
      }
    }
    case 'LspInstallResolved':
      return { ...state, events, lspInstallRequest: null }
    // §10 sub-agent panel reducer arms.
    case 'SubagentSpawned': {
      const p = evt.payload as {
        id: string
        subagent_type: string
        description: string
        max_turns: number
      }
      const entry: SubagentEntry = {
        id: p.id,
        subagentType: p.subagent_type ?? '',
        description: p.description ?? '',
        status: 'running',
        turn: 0,
        maxTurns: p.max_turns ?? 0,
        promptTokens: 0,
        completionTokens: 0,
        cachedTokens: 0,
        generation: state.currentGeneration,
      }
      return { ...state, events, subagents: [...state.subagents, entry] }
    }
    case 'SubagentTurnAdvanced': {
      const p = evt.payload as { id: string; turn: number }
      const subagents = updateSubagentById(state.subagents, p.id, (e) =>
        ({ ...e, turn: p.turn ?? e.turn }),
      )
      return { ...state, events, subagents }
    }
    case 'SubagentToolCall':
      // No state change — event-log entry is sufficient.
      return { ...state, events }
    case 'SubagentTokensUpdated': {
      const p = evt.payload as {
        id: string
        prompt_tokens: number
        completion_tokens: number
        cached_tokens: number
      }
      const subagents = updateSubagentById(state.subagents, p.id, (e) =>
        ({
          ...e,
          promptTokens: p.prompt_tokens ?? e.promptTokens,
          completionTokens: p.completion_tokens ?? e.completionTokens,
          cachedTokens: p.cached_tokens ?? e.cachedTokens,
        }),
      )
      return { ...state, events, subagents }
    }
    case 'SubagentCompleted': {
      const p = evt.payload as { id: string; status: string; turns_used: number }
      const subagents = updateSubagentById(state.subagents, p.id, (e) =>
        ({ ...e, status: p.status ?? 'completed', turn: p.turns_used ?? e.turn }),
      )
      return { ...state, events, subagents }
    }
    case 'SubagentCancelled': {
      const p = evt.payload as { id: string }
      const subagents = updateSubagentById(state.subagents, p.id, (e) => ({ ...e, status: 'cancelled' }))
      return { ...state, events, subagents }
    }
    case 'AgentStalled':
      // Model replied without tool calls or a claimed_done envelope —
      // runner is waiting for user input. Surface a banner.
      return { ...state, events, stalledAt: Date.now() }
    case 'RunStarted':
      return { ...state, events, runInFlight: true }
    case 'RunFinished':
      return { ...state, events, runInFlight: false }
    // Variants we don't fold into pane state — just the event log.
    case 'IllegalTransitionAttempted':
    case 'Cancelled':
    case 'Shutdown':
      return { ...state, events }
    default: {
      // v60.30 — surface unknown event variants instead of silently
      // dropping them.
      //
      // v60.41 — softened from `throw` in DEV to plain `console.error`.
      // The throw fired the Rust side ever emitted a variant the
      // reducer didn't yet have a case for (e.g. `VerificationFailed`),
      // and that aborted the listener callback for that event. The
      // shape-contract enforcement role moved to per-arm `castPayload`
      // guards (v60.37 B6), which catch the failure mode the throw was
      // protecting against — payload-field drift on KNOWN events. An
      // unknown KIND is now a non-fatal "Rust grew an event the UI
      // doesn't yet care about" signal.
      console.error('Unknown event variant', evt.kind, evt)
      return { ...state, events }
    }
  }
}

// ---- Scrubber commands. Mirror of TUI ScrubCommand. ----

export type ScrubCommand = 'prev' | 'next' | 'head'

export function applyScrub(state: AppState, cmd: ScrubCommand): AppState {
  let next: number | null
  switch (cmd) {
    case 'head':
      next = null
      break
    case 'prev':
      next = (state.scrubOffset ?? 0) + 1
      break
    case 'next': {
      if (state.scrubOffset == null) {
        next = null
      } else {
        const n = state.scrubOffset - 1
        next = n <= 0 ? null : n
      }
      break
    }
  }
  return { ...state, scrubOffset: next }
}

// ---- helpers ----

function nowTimestamp(): string {
  const d = new Date()
  const hh = String(d.getHours()).padStart(2, '0')
  const mm = String(d.getMinutes()).padStart(2, '0')
  const ss = String(d.getSeconds()).padStart(2, '0')
  const ms = String(d.getMilliseconds()).padStart(3, '0')
  return `${hh}:${mm}:${ss}:${ms}`
}

function pushBounded<T>(arr: T[], item: T, cap: number): T[] {
  const next = [...arr, item]
  if (next.length <= cap) return next
  return next.slice(next.length - cap)
}

function pushBoundedNewest<T>(arr: T[], item: T, cap: number): T[] {
  if (cap <= 0) return []
  if (arr.length < cap) return [item, ...arr]
  return [item, ...arr.slice(0, cap - 1)]
}

function updateSubagentById(
  subagents: SubagentEntry[],
  id: string,
  update: (entry: SubagentEntry) => SubagentEntry,
): SubagentEntry[] {
  const idx = subagents.findIndex((entry) => entry.id === id)
  if (idx < 0) return subagents
  const next = subagents.slice()
  next[idx] = update(subagents[idx])
  return next
}

function ledgerEntryCost(entry: LedgerEntry): number | null {
  switch (entry.kind) {
    case 'model_call':
    case 'tool_call':
      return entry.cost_usd ?? null
    case 'cache_bust':
      // CacheBust entries carry no cost field — see TUI comment.
      return null
  }
}

function isConversationRole(s: string): s is ConversationRole {
  return s === 'user' || s === 'assistant' || s === 'tool' || s === 'system'
}

/// v62 — type-guard for the wire label of a `VerificationTier`.
/// Matches the Rust serde labels (`rename_all = "snake_case"`).
function isVerificationTier(s: string): s is VerificationTier {
  return (
    s === 'tier1_lsp' ||
    s === 'tier2_tree_sitter' ||
    s === 'tier3_textual' ||
    s === 'not_run'
  )
}

/// v62 — human-readable label for the verify-pass badge. Mirrors
/// the TUI's badge text so the two surfaces stay in sync. Exported
/// so `MetersPane.svelte` and any future verify-pass UI render
/// identical copy.
export function verificationTierLabel(tier: VerificationTier): string {
  switch (tier) {
    case 'tier1_lsp':
      return 'tier-1 (lsp)'
    case 'tier2_tree_sitter':
      return 'tier-2 (tree-sitter)'
    case 'tier3_textual':
      return 'tier-3 (textual)'
    case 'not_run':
      return 'verify off'
  }
}

export function projectEvent(evt: BridgedEvent): Omit<EventLogEntry, 'ts'> {
  // v58 (H7-residual + GUI label-drift fix) — `kind` comes from the
  // BridgedEvent's `kind` field, which is sourced from Rust's
  // `SessionEvent::kind()` (canonical variant names). Pre-v58 this
  // function synthesised its own short labels (Message,
  // PendingApproval, IllegalTransition, ModelProfile) which drifted
  // from the TUI projection by construction.
  const kind = evt.kind
  switch (evt.kind) {
    case 'MessageCommitted': {
      const p = evt.payload as { role: string; text: string }
      const firstLine = (p.text ?? '').split('\n')[0] ?? ''
      return { kind, detail: `${p.role}: ${firstLine.slice(0, 60)}` }
    }
    case 'AssistantTextDelta': {
      const p = evt.payload as { delta: string }
      return { kind, detail: `+${(p.delta ?? '').length}chars` }
    }
    case 'LedgerAppended': {
      const p = evt.payload as { entry: LedgerEntry }
      const label = p.entry.kind === 'tool_call' ? `tool_call:${p.entry.tool_name}` : p.entry.kind
      return { kind, detail: label }
    }
    case 'ContextSnapshot': {
      const p = evt.payload as { known_tokens: number; unknown_tokens: number }
      return {
        kind,
        detail: `known=${p.known_tokens} unknown=${p.unknown_tokens}`,
      }
    }
    case 'Transitioned': {
      const p = evt.payload as { from: string; to: string }
      return { kind, detail: `${p.from} → ${p.to}` }
    }
    case 'IllegalTransitionAttempted': {
      const p = evt.payload as { from: string; to: string }
      return { kind, detail: `${p.from} ↛ ${p.to}` }
    }
    case 'ModelProfileLoaded': {
      const p = evt.payload as { model_id: string; strategy: string; outcome: string }
      return {
        kind,
        detail: `${p.model_id} · strategy=${p.strategy} · ${p.outcome}`,
      }
    }
    case 'ContextItems': {
      const p = evt.payload as { items?: unknown[] }
      const n = Array.isArray(p.items) ? p.items.length : 0
      return { kind, detail: `${n} items` }
    }
    case 'MemoryCards': {
      const p = evt.payload as { cards?: unknown[] }
      const n = Array.isArray(p.cards) ? p.cards.length : 0
      return { kind, detail: `${n} cards` }
    }
    case 'MentalModelSnapshot': {
      const p = evt.payload as { enabled?: boolean; text_tokens?: number }
      return {
        kind,
        detail: `${p.enabled ? 'on' : 'off'} · ~${p.text_tokens ?? 0} tokens`,
      }
    }
    case 'Cancelled':
      return { kind, detail: '' }
    case 'Shutdown':
      return { kind, detail: '' }
    case 'FilesChanged': {
      const p = evt.payload as { paths?: unknown[]; observed_at?: string }
      const n = Array.isArray(p.paths) ? p.paths.length : 0
      return { kind, detail: `${n} path(s) changed at ${p.observed_at ?? ''}` }
    }
    case 'FilesChangedAcknowledged': {
      const p = evt.payload as { outcome?: string }
      return { kind, detail: p.outcome ?? '' }
    }
    case 'VerificationPassed': {
      const p = evt.payload as {
        tier?: string
        file_count?: number
        claim_count?: number
      }
      const tier = isVerificationTier(p.tier ?? '') ? (p.tier as VerificationTier) : 'not_run'
      const files = p.file_count ?? 0
      const claims = p.claim_count ?? 0
      return {
        kind,
        detail: `${verificationTierLabel(tier)} · ${files} files · ${claims} claims`,
      }
    }
    case 'ContextOverflowResolved': {
      const p = evt.payload as {
        resolution?: string
        freed_tokens?: number | null
        items_compacted?: number | null
      }
      const resolution = p.resolution ?? '?'
      const t = p.freed_tokens
      const n = p.items_compacted
      if (t != null && n != null) {
        return { kind, detail: `${resolution} · ${n} items · ${t} tokens` }
      }
      return { kind, detail: resolution }
    }
    case 'StrategyDegraded': {
      const p = evt.payload as { from?: string; to?: string; reason?: string }
      return {
        kind,
        detail: `${p.from ?? '?'} → ${p.to ?? '?'} (${p.reason ?? ''})`,
      }
    }
    case 'AdapterSwapped': {
      // v60.10 §1 BYOM — render the swap pair in the event log so the
      // user can see "anthropic:x → local:y" alongside the paired
      // `ModelProfileLoaded` that refreshes the model badge.
      const p = evt.payload as {
        from_model_id?: string
        to_model_id?: string
        swapped_at?: string
      }
      return {
        kind,
        detail: `${p.from_model_id ?? '?'} → ${p.to_model_id ?? '?'}`,
      }
    }
    case 'AdapterSwapPending': {
      // v60.28 H2 follow-on — one-line summary of the pending swap; the
      // consent modal in App.svelte is the user-facing surface.
      const p = evt.payload as { to_model_id?: string; base_url?: string }
      const base = p.base_url ? ` (${p.base_url})` : ''
      return { kind, detail: `pending → ${p.to_model_id ?? '?'}${base}` }
    }
    case 'AdapterSwapRejected': {
      // v60.28 H2 follow-on — one-line summary of the rejection so the
      // user can see the reason in the event log even after the modal
      // closes.
      const p = evt.payload as { to_model_id?: string; reason?: string }
      return {
        kind,
        detail: `rejected → ${p.to_model_id ?? '?'}: ${p.reason ?? '?'}`,
      }
    }
    // Phase B Track C1 prep — §7 Tier-1 LSP first-use install events.
    // One-line event-log rendering until the approval modal lands.
    case 'RequestLspInstall': {
      const p = evt.payload as {
        language?: string
        candidate_packages?: string[]
      }
      return {
        kind,
        detail: `${p.language ?? '?'}: install ${(p.candidate_packages ?? []).join(', ')}`,
      }
    }
    case 'LspInstallResolved': {
      const p = evt.payload as { language?: string; outcome?: string }
      return {
        kind,
        detail: `${p.language ?? '?'}: ${p.outcome ?? '?'}`,
      }
    }
    case 'SubagentSpawned': {
      const p = evt.payload as {
        id?: string
        subagent_type?: string
        description?: string
        max_turns?: number
      }
      return {
        kind,
        detail: `[${p.id ?? '?'}] ${p.subagent_type ?? '?'}: "${p.description ?? ''}" (max ${p.max_turns ?? 0} turns)`,
      }
    }
    case 'SubagentTurnAdvanced': {
      const p = evt.payload as { id?: string; turn?: number; max_turns?: number }
      return {
        kind,
        detail: `[${p.id ?? '?'}] turn ${p.turn ?? '?'}/${p.max_turns ?? '?'}`,
      }
    }
    case 'SubagentToolCall': {
      const p = evt.payload as { id?: string; tool?: string }
      return { kind, detail: `[${p.id ?? '?'}] tool: ${p.tool ?? '?'}` }
    }
    case 'SubagentTokensUpdated': {
      const p = evt.payload as {
        id?: string
        prompt_tokens?: number
        completion_tokens?: number
        cached_tokens?: number
      }
      return {
        kind,
        detail: `[${p.id ?? '?'}] ↑${p.prompt_tokens ?? 0} ↓${p.completion_tokens ?? 0} cached ${p.cached_tokens ?? 0}`,
      }
    }
    case 'SubagentCompleted': {
      const p = evt.payload as { id?: string; status?: string; turns_used?: number }
      return {
        kind,
        detail: `[${p.id ?? '?'}] ${p.status ?? '?'} after ${p.turns_used ?? '?'} turns`,
      }
    }
    case 'SubagentCancelled': {
      const p = evt.payload as { id?: string; reason?: string }
      return { kind, detail: `[${p.id ?? '?'}] cancelled: ${p.reason ?? '?'}` }
    }
    case 'AgentStalled': {
      const p = evt.payload as { turn?: number; reason?: string }
      return { kind, detail: `turn ${p.turn ?? '?'}: ${p.reason ?? 'no tool calls or claimed_done'}` }
    }
    case 'RunStarted':
      return { kind, detail: 'runner starting…' }
    case 'RunFinished':
      return { kind, detail: 'runner done' }
    default:
      return { kind, detail: '' }
  }
}

// ---- role colour mapping ----
//
// Single source of truth so the conversation pane and any future
// transcript-export feature stay in sync. Matches TUI palette.

export function roleColour(role: ConversationRole): string {
  switch (role) {
    case 'user':
      return 'var(--role-user)'
    case 'assistant':
      return 'var(--role-assistant)'
    case 'tool':
      return 'var(--role-tool)'
    case 'system':
      return 'var(--role-system)'
  }
}
